### ISSUE TITLE
Can you provide the data?

### ISSUE THREAD

**Issue by chdjianfeng** [HakamShams/Semantic-Mesh-Segmentation#1]
Hello! Thank you for sharing the source code. I'm very interested in this project. Can you provide a sample data? Thank you very much.

**Comment by HakamShams** [comment]
Hallo, thank you for your interest. As far as I know the data is subject to copyright. It belongs to the Institute of Photogrammetry, Uni Stuttgart (ifp) and the German Federal Institute of Hydrology (BfG).
However, you can contact Prof. Haala (norbert.haala@ifp.uni-stuttgart.de) or Mr. Laupheimer (dominik.laupheimer@ifp.uni-stuttgart.de) from ifp. They may help you.

**Comment by chdjianfeng** [comment]
Ok! Thank you!
